language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"

# command to install dependencies
install:
 - pip install -r requirements.txt --upgrade
 - pip install flake8
 - pip install coveralls

# command to execute test suite
script:
 - flake8 .
 - nosetests --with-coverage --cover-package=IOHMM

# Send results of tests to coveralls
after_success:
 - coveralls
